# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sirhall/Documents/GitRepos/nQueens

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sirhall/Documents/GitRepos/nQueens

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sirhall/Documents/GitRepos/nQueens/CMakeFiles /home/sirhall/Documents/GitRepos/nQueens/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sirhall/Documents/GitRepos/nQueens/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nQueen

# Build rule for target.
nQueen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nQueen
.PHONY : nQueen

# fast build rule for target.
nQueen/fast:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/build
.PHONY : nQueen/fast

src/Misc/MathMore.o: src/Misc/MathMore.cpp.o

.PHONY : src/Misc/MathMore.o

# target to build an object file
src/Misc/MathMore.cpp.o:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/Misc/MathMore.cpp.o
.PHONY : src/Misc/MathMore.cpp.o

src/Misc/MathMore.i: src/Misc/MathMore.cpp.i

.PHONY : src/Misc/MathMore.i

# target to preprocess a source file
src/Misc/MathMore.cpp.i:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/Misc/MathMore.cpp.i
.PHONY : src/Misc/MathMore.cpp.i

src/Misc/MathMore.s: src/Misc/MathMore.cpp.s

.PHONY : src/Misc/MathMore.s

# target to generate assembly for a file
src/Misc/MathMore.cpp.s:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/Misc/MathMore.cpp.s
.PHONY : src/Misc/MathMore.cpp.s

src/Misc/ProgressBar.o: src/Misc/ProgressBar.cpp.o

.PHONY : src/Misc/ProgressBar.o

# target to build an object file
src/Misc/ProgressBar.cpp.o:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/Misc/ProgressBar.cpp.o
.PHONY : src/Misc/ProgressBar.cpp.o

src/Misc/ProgressBar.i: src/Misc/ProgressBar.cpp.i

.PHONY : src/Misc/ProgressBar.i

# target to preprocess a source file
src/Misc/ProgressBar.cpp.i:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/Misc/ProgressBar.cpp.i
.PHONY : src/Misc/ProgressBar.cpp.i

src/Misc/ProgressBar.s: src/Misc/ProgressBar.cpp.s

.PHONY : src/Misc/ProgressBar.s

# target to generate assembly for a file
src/Misc/ProgressBar.cpp.s:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/Misc/ProgressBar.cpp.s
.PHONY : src/Misc/ProgressBar.cpp.s

src/board/Board.o: src/board/Board.cpp.o

.PHONY : src/board/Board.o

# target to build an object file
src/board/Board.cpp.o:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/board/Board.cpp.o
.PHONY : src/board/Board.cpp.o

src/board/Board.i: src/board/Board.cpp.i

.PHONY : src/board/Board.i

# target to preprocess a source file
src/board/Board.cpp.i:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/board/Board.cpp.i
.PHONY : src/board/Board.cpp.i

src/board/Board.s: src/board/Board.cpp.s

.PHONY : src/board/Board.s

# target to generate assembly for a file
src/board/Board.cpp.s:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/board/Board.cpp.s
.PHONY : src/board/Board.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/queen/Queen.o: src/queen/Queen.cpp.o

.PHONY : src/queen/Queen.o

# target to build an object file
src/queen/Queen.cpp.o:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/queen/Queen.cpp.o
.PHONY : src/queen/Queen.cpp.o

src/queen/Queen.i: src/queen/Queen.cpp.i

.PHONY : src/queen/Queen.i

# target to preprocess a source file
src/queen/Queen.cpp.i:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/queen/Queen.cpp.i
.PHONY : src/queen/Queen.cpp.i

src/queen/Queen.s: src/queen/Queen.cpp.s

.PHONY : src/queen/Queen.s

# target to generate assembly for a file
src/queen/Queen.cpp.s:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/queen/Queen.cpp.s
.PHONY : src/queen/Queen.cpp.s

src/search_results/SearchResults.o: src/search_results/SearchResults.cpp.o

.PHONY : src/search_results/SearchResults.o

# target to build an object file
src/search_results/SearchResults.cpp.o:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/search_results/SearchResults.cpp.o
.PHONY : src/search_results/SearchResults.cpp.o

src/search_results/SearchResults.i: src/search_results/SearchResults.cpp.i

.PHONY : src/search_results/SearchResults.i

# target to preprocess a source file
src/search_results/SearchResults.cpp.i:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/search_results/SearchResults.cpp.i
.PHONY : src/search_results/SearchResults.cpp.i

src/search_results/SearchResults.s: src/search_results/SearchResults.cpp.s

.PHONY : src/search_results/SearchResults.s

# target to generate assembly for a file
src/search_results/SearchResults.cpp.s:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/search_results/SearchResults.cpp.s
.PHONY : src/search_results/SearchResults.cpp.s

src/solvers/Solver_BFS.o: src/solvers/Solver_BFS.cpp.o

.PHONY : src/solvers/Solver_BFS.o

# target to build an object file
src/solvers/Solver_BFS.cpp.o:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_BFS.cpp.o
.PHONY : src/solvers/Solver_BFS.cpp.o

src/solvers/Solver_BFS.i: src/solvers/Solver_BFS.cpp.i

.PHONY : src/solvers/Solver_BFS.i

# target to preprocess a source file
src/solvers/Solver_BFS.cpp.i:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_BFS.cpp.i
.PHONY : src/solvers/Solver_BFS.cpp.i

src/solvers/Solver_BFS.s: src/solvers/Solver_BFS.cpp.s

.PHONY : src/solvers/Solver_BFS.s

# target to generate assembly for a file
src/solvers/Solver_BFS.cpp.s:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_BFS.cpp.s
.PHONY : src/solvers/Solver_BFS.cpp.s

src/solvers/Solver_BFS_Fast.o: src/solvers/Solver_BFS_Fast.cpp.o

.PHONY : src/solvers/Solver_BFS_Fast.o

# target to build an object file
src/solvers/Solver_BFS_Fast.cpp.o:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_BFS_Fast.cpp.o
.PHONY : src/solvers/Solver_BFS_Fast.cpp.o

src/solvers/Solver_BFS_Fast.i: src/solvers/Solver_BFS_Fast.cpp.i

.PHONY : src/solvers/Solver_BFS_Fast.i

# target to preprocess a source file
src/solvers/Solver_BFS_Fast.cpp.i:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_BFS_Fast.cpp.i
.PHONY : src/solvers/Solver_BFS_Fast.cpp.i

src/solvers/Solver_BFS_Fast.s: src/solvers/Solver_BFS_Fast.cpp.s

.PHONY : src/solvers/Solver_BFS_Fast.s

# target to generate assembly for a file
src/solvers/Solver_BFS_Fast.cpp.s:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_BFS_Fast.cpp.s
.PHONY : src/solvers/Solver_BFS_Fast.cpp.s

src/solvers/Solver_Base.o: src/solvers/Solver_Base.cpp.o

.PHONY : src/solvers/Solver_Base.o

# target to build an object file
src/solvers/Solver_Base.cpp.o:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_Base.cpp.o
.PHONY : src/solvers/Solver_Base.cpp.o

src/solvers/Solver_Base.i: src/solvers/Solver_Base.cpp.i

.PHONY : src/solvers/Solver_Base.i

# target to preprocess a source file
src/solvers/Solver_Base.cpp.i:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_Base.cpp.i
.PHONY : src/solvers/Solver_Base.cpp.i

src/solvers/Solver_Base.s: src/solvers/Solver_Base.cpp.s

.PHONY : src/solvers/Solver_Base.s

# target to generate assembly for a file
src/solvers/Solver_Base.cpp.s:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_Base.cpp.s
.PHONY : src/solvers/Solver_Base.cpp.s

src/solvers/Solver_HillDescent.o: src/solvers/Solver_HillDescent.cpp.o

.PHONY : src/solvers/Solver_HillDescent.o

# target to build an object file
src/solvers/Solver_HillDescent.cpp.o:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_HillDescent.cpp.o
.PHONY : src/solvers/Solver_HillDescent.cpp.o

src/solvers/Solver_HillDescent.i: src/solvers/Solver_HillDescent.cpp.i

.PHONY : src/solvers/Solver_HillDescent.i

# target to preprocess a source file
src/solvers/Solver_HillDescent.cpp.i:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_HillDescent.cpp.i
.PHONY : src/solvers/Solver_HillDescent.cpp.i

src/solvers/Solver_HillDescent.s: src/solvers/Solver_HillDescent.cpp.s

.PHONY : src/solvers/Solver_HillDescent.s

# target to generate assembly for a file
src/solvers/Solver_HillDescent.cpp.s:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_HillDescent.cpp.s
.PHONY : src/solvers/Solver_HillDescent.cpp.s

src/solvers/Solver_SimAnnealing.o: src/solvers/Solver_SimAnnealing.cpp.o

.PHONY : src/solvers/Solver_SimAnnealing.o

# target to build an object file
src/solvers/Solver_SimAnnealing.cpp.o:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_SimAnnealing.cpp.o
.PHONY : src/solvers/Solver_SimAnnealing.cpp.o

src/solvers/Solver_SimAnnealing.i: src/solvers/Solver_SimAnnealing.cpp.i

.PHONY : src/solvers/Solver_SimAnnealing.i

# target to preprocess a source file
src/solvers/Solver_SimAnnealing.cpp.i:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_SimAnnealing.cpp.i
.PHONY : src/solvers/Solver_SimAnnealing.cpp.i

src/solvers/Solver_SimAnnealing.s: src/solvers/Solver_SimAnnealing.cpp.s

.PHONY : src/solvers/Solver_SimAnnealing.s

# target to generate assembly for a file
src/solvers/Solver_SimAnnealing.cpp.s:
	$(MAKE) -f CMakeFiles/nQueen.dir/build.make CMakeFiles/nQueen.dir/src/solvers/Solver_SimAnnealing.cpp.s
.PHONY : src/solvers/Solver_SimAnnealing.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... nQueen"
	@echo "... edit_cache"
	@echo "... src/Misc/MathMore.o"
	@echo "... src/Misc/MathMore.i"
	@echo "... src/Misc/MathMore.s"
	@echo "... src/Misc/ProgressBar.o"
	@echo "... src/Misc/ProgressBar.i"
	@echo "... src/Misc/ProgressBar.s"
	@echo "... src/board/Board.o"
	@echo "... src/board/Board.i"
	@echo "... src/board/Board.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/queen/Queen.o"
	@echo "... src/queen/Queen.i"
	@echo "... src/queen/Queen.s"
	@echo "... src/search_results/SearchResults.o"
	@echo "... src/search_results/SearchResults.i"
	@echo "... src/search_results/SearchResults.s"
	@echo "... src/solvers/Solver_BFS.o"
	@echo "... src/solvers/Solver_BFS.i"
	@echo "... src/solvers/Solver_BFS.s"
	@echo "... src/solvers/Solver_BFS_Fast.o"
	@echo "... src/solvers/Solver_BFS_Fast.i"
	@echo "... src/solvers/Solver_BFS_Fast.s"
	@echo "... src/solvers/Solver_Base.o"
	@echo "... src/solvers/Solver_Base.i"
	@echo "... src/solvers/Solver_Base.s"
	@echo "... src/solvers/Solver_HillDescent.o"
	@echo "... src/solvers/Solver_HillDescent.i"
	@echo "... src/solvers/Solver_HillDescent.s"
	@echo "... src/solvers/Solver_SimAnnealing.o"
	@echo "... src/solvers/Solver_SimAnnealing.i"
	@echo "... src/solvers/Solver_SimAnnealing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

